site_name: Time Series Statistical Tests
site_dir: www
site_author: chrimaho
site_description: A suite of statistical tests for time-series data
repo_name: "chrimaho/ts-stat-tests"
repo_url: https://github.com/chrimaho/ts-stat-tests
docs_dir: docs

theme:
    name: material
    custom_dir: docs
    palette:
        primary: teal
        accent: indigo
    features:
        - navigation.instant
        - navigation.sections
        - navigation.expand
        - navigation.tracking
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
    highightjs: true
    hljs_languages:
        - yaml
        - python
    icon:
        repo: fontawesome/brands/github

markdown_extensions:
    - admonition
    - meta
    - md_in_html
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.snippets:
          check_paths: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: "!!python/name:pymdownx.superfences.fence_code_format"
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
          # clickable_checkbox: true
    - pymdownx.details
    - toc:
          permalink: "🔗"
          # permalink_class: anchor
          # anchorlink: true

nav:
    - Home: docs/index.md
    - Docs:
          - Tests:
                - Stability: docs/docs/overview.md
    - Code:
          - Overview: docs/code/overview.md
          - Tests:
                - Stability: docs/code/stability.md
                - Correlation: docs/code/correlation.md

extra_css:
    - css/style.css

plugins:
    - search:
          indexing: full
          prebuild_index: true
    # - section-index
    - autorefs
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  selection:
                      docstring_style: google
                      docstring_options:
                          replace_admonitions: no
                  rendering:
                      show_root_heading: true
                      show_root_toc_entry: false
                      show_root_full_path: false
                      show_source: true
                      show_object_full_path: false
                      show_signature_annotations: true
                      show_category_heading: false
                      show_if_no_docstring: true
                      heading_level: 3
                      members_order: source
                      group_by_category: false
          watch:
              - src
