name: Code Coverage
on:
  - push
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Fetch
        uses: actions/checkout@master

      - name: Set Up
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Prepare
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv --python 3.9 install --requirements requirements-tst.txt --ignore-pipfile --no-site-packages --skip-lock
          pipenv --python 3.9 install --requirements requirements.txt --ignore-pipfile --no-site-packages --skip-lock

      - name: Test
        run: |
          pipenv run pytest --cov=ts_stat_tests

      - name: Upload
        uses: codecov/codecov-action@v2
