name: test suite

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:

      - name: Fetch
        uses: actions/checkout@master

      - name: Set Up
        uses: actions/setup-python@main
        with:
          python-version: "3.9"

      - name: Prepare
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv --python 3.9 install --requirements requirements.txt --requirements requirements-tst.txt --ignore-pipfile --no-site-packages --skip-lock

      - name: Test
        run: |
          pipenv run pytest --verbose --cov=src --cov-report=term --cov-report=html:cov-report/html --cov-report=xml:cov-report/xml/cov-report.xml

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          files: ./cov-report/xml/cov-report.xml
