name: docs build 
on:
  push:
    branches:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install --upgrade pip
      - run: pip install --requirement requirements-doc.txt
      - run: mkdocs gh-deploy --force

# Will be deployed to: https://chrimaho.github.io/ts-stat-tests/
